In [6]:
import numpy as np

def truncated_svd_poster_example():
    # ---- Fixed poster input (NaN = missing ratings) ----
    R = np.array([
        [5, np.nan, 4, 1, np.nan],
        [5, 3, np.nan, np.nan, np.nan],
        [np.nan, 3, 2, np.nan, 1],
        [np.nan, np.nan, np.nan, 4, 2]
    ], dtype=float)

    # ---- Fill missing values using column mean ----
    col_mean = np.nanmean(R, axis=0)
    R_filled = np.where(np.isnan(R), col_mean, R)

    # ---- Built-in SVD ----
    U, S, Vt = np.linalg.svd(R_filled, full_matrices=False)

    # ---- Truncation ----
    k = 2   # latent factors
    U_k = U[:, :k]
    S_k = np.diag(S[:k])
    Vt_k = Vt[:k, :]

    # ---- Reconstruction ----
    R_hat = U_k @ S_k @ Vt_k

    # ---- RMSE (only on known ratings) ----
    mask = ~np.isnan(R)
    rmse = np.sqrt(np.mean((R[mask] - R_hat[mask]) ** 2))

    # ---- OUTPUT ONLY ----
    print("Original Rating Matrix:")
    print(R)

    print("\nReconstructed Rating Matrix (Truncated SVD):")
    print(np.round(R_hat, 2))

    print("\nRMSE:", round(rmse, 2))


# ---- Run ----
truncated_svd_poster_example()

Original Rating Matrix:
[[ 5. nan  4.  1. nan]
 [ 5.  3. nan nan nan]
 [nan  3.  2. nan  1.]
 [nan nan nan  4.  2.]]

Reconstructed Rating Matrix (Truncated SVD):
[[5.1  3.06 3.87 0.95 1.4 ]
 [4.99 2.99 3.02 2.51 1.51]
 [4.57 2.74 2.56 2.73 1.43]
 [5.29 3.17 2.62 3.84 1.71]]

RMSE: 0.26
